baseurl = "http://example.org"
title = "Rogue Productions"
theme = "dimension"
languageCode = "fr-fr"
defaultContentLanguage = "fr"
enableRobotsTXT = true
disableRSS = true

[params]
  title = "Rogue Productions"
  description = "mécaniciens de l'immatériel"
  logo = "fa-space-shuttle"
  copyright = "Untitled"

[[params.social]]
  medium = "twitter"
  icon = "twitter"
  link = "#"

[[params.social]]
  medium = "facebook"
  icon = "facebook"
  link = "#"

[[params.social]]
  medium = "instagram"
  icon = "instagram"
  link = "#"

[[params.social]]
  medium = "github"
  icon = "github"
  link = "#"

[languages]
[languages.fr]
languageName = "Français"
weight = 1
title = "Rogue Productions"

[languages.en]
languageName = "English"
weight = 2
title = "Rogue Productions"
description = '<!--[--> <!--]--><br />
                <!--[-->.<!--]-->'
